### ISSUE TITLE
Erro ao Cancelar nfe

### ISSUE THREAD

**Issue by FelipeLopes360** [Trust-Code/odoo-brazil-eletronic-documents#20]
Teste realizado em ambiente de homologação.
Versão do Odoo: 8.0
Localização Brasil - > Cancelar documento fiscal ->Selecionado fatura e preenchido justificativa.
O seguinte erro é apresentado:

Traceback (most recent call last):
File "/opt/odoo/openerp/http.py", line 543, in handle_exception
return super(JsonRequest, self).handle_exception(exception)
File "/opt/odoo/openerp/http.py", line 580, in dispatch
result = self._call_function(*self.params)
File "/opt/odoo/openerp/http.py", line 316, in _call_function
return checked_call(self.db, *args, *kwargs)
File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
return f(dbname, args, *kwargs)
File "/opt/odoo/openerp/http.py", line 313, in checked_call
return self.endpoint(a, *kw)
File "/opt/odoo/openerp/http.py", line 809, in __call
return self.method(args, *kw)
File "/opt/odoo/openerp/http.py", line 409, in response_wrap
response = f(args, *kw)
File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
action = self._call_kw(model, method, args, {})
File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
File "/opt/odoo/openerp/api.py", line 268, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/openerp/api.py", line 399, in old_api
result = method(recs, args, *kwargs)
File "/opt/odoo/br/odoo-brazil-eletronic-documents/nfe/models/l10n_br_account.py", line 142, in action_draft_done
record.invoice_id.id, 'invoice_cancel')
TypeError: trg_validate() takes exactly 5 arguments (3 given)

**Comment by FelipeLopes360** [comment]
os argumentos do trg_validate não devia ser como na documentação? 
def openerp.workflow.trg_validate(uid, res_type, res_id, signal, cr)

**Comment by FelipeLopes360** [comment]
Realizado teste em Contabilidade->Faturas de Clientes e realizado o cancelamento a apartir da fatura no botão "Cancelar Fatura" e preenchido o motivo.
Em eventos eletrônicos é retornado o cod 000 "Erro desconhecido"
Eu estou realizando o cancelamento de forma errada ou é bug?

**Comment by danimaribeiro** [comment]
Parece ser bug sim, recentemente foi migrado para a nova API, deve ser decorrência disto.

**Comment by danimaribeiro** [comment]
Pode usar o cancelamento diretamente na nota fiscal.
Lá está funcionando corretamente.

**Comment by FelipeLopes360** [comment]
Se cancelar diretamente pela nota fiscal em Eventos Eletrônicos é retornado 000 Erro desconhecido.
Lembrando que estou em ambiente de homologação.

**Comment by danimaribeiro** [comment]
Vais ter que analisar teu log para ver o erro que está acontecendo.

**Comment by FelipeLopes360** [comment]
Obrigado! Achei a solução, para cancelar a nfe no SEFAZ é necessário habilitar a opção "Permite cancelar lançamentos" em Contabilidade->Configurações->Diários->Diários->Diário de Vendas.

**Comment by pcastilho** [comment]
Eu habilitei está configuração no diário porem ainda continua dando erro reportado no inicio da discussão.

Alguém pode me dizer se tem algum problema com a localização brasileira ou se falta de configuração do sistema?
