### ISSUE TITLE
Erro no manifesto

### ISSUE THREAD

**Issue by FelipeLopes360** [Trust-Code/odoo-brazil-eletronic-documents#26]
ao clicar em "Verificar NFe para download" o seguinte erro ocorre:

`2016-09-21 12:12:12,729 1635 ERROR testesMDE openerp.addons.nfe_mde.nfe_schedule: Erro ao consultar Manifesto
Traceback (most recent call last):
  File "/opt/odoo/tt/odoo-brazil-eletronic-documents/nfe_mde/nfe_schedule.py", line 58, in schedule_download
    nfe_result = distribuicao_nfe(company, company.last_nsu_nfe)
  File "/opt/odoo/tt/odoo-brazil-eletronic-documents/nfe_mde/service/mde.py", line 51, in distribuicao_nfe
    nsu='')
  File "/usr/local/lib/python2.7/dist-packages/pysped/nfe/processador_nfe.py", line 1388, in consultar_distribuicao
    self._conectar_servico(WS_DFE_DISTRIBUICAO, envio, resposta, somente_ambiente_nacional=True)
  File "/usr/local/lib/python2.7/dist-packages/pysped/nfe/processador_nfe.py", line 310, in _conectar_servico
    self.certificado.prepara_certificado_arquivo_pfx()
  File "/usr/local/lib/python2.7/dist-packages/pysped/xml_sped/certificado.py", line 85, in prepara_certificado_arquivo_pfx
    pkcs12 = crypto.load_pkcs12(self.stream_certificado, self.senha)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2223, in load_pkcs12
    parse_result = _lib.PKCS12_parse(p12, passphrase, pkey, cert, cacerts)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode
`

**Comment by FelipeLopes360** [comment]
Pensei que poderia ser algo no pysped e reinstalei tudo conforme o dockerfile da TrustCode. O mesmo erro foi apresentado:

`
Traceback (most recent call last):
  File "/opt/odoo/tt/odoo-brazil-eletronic-documents/nfe_mde/nfe_schedule.py", line 58, in schedule_download
    nfe_result = distribuicao_nfe(company, company.last_nsu_nfe)
  File "/opt/odoo/tt/odoo-brazil-eletronic-documents/nfe_mde/service/mde.py", line 51, in distribuicao_nfe
    nsu='')
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/nfe/processador_nfe.py", line 1310, in consultar_distribuicao
    self._conectar_servico(WS_DFE_DISTRIBUICAO, envio, resposta, somente_ambiente_nacional=True)
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/nfe/processador_nfe.py", line 310, in _conectar_servico
    self.certificado.prepara_certificado_arquivo_pfx()
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/xml_sped/certificado.py", line 85, in prepara_certificado_arquivo_pfx
    pkcs12 = crypto.load_pkcs12(self.stream_certificado, self.senha)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2223, in load_pkcs12
    parse_result = _lib.PKCS12_parse(p12, passphrase, pkey, cert, cacerts)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode

`

**Comment by FelipeLopes360** [comment]
Problema resolvido. Eu estava utilizando Debian e por algum motivo estava gerando este erro(Instalei todos os pacotes). No ubuntu funcionou normalmente.
