### ISSUE TITLE
Error on generate DANFE

### ISSUE THREAD

**Issue by yk2kus** [Trust-Code/odoo-brazil-eletronic-documents#4]
File "/opt/openerp-8.0/odoo-brazil-eletronic-documents/nfe/report/report.py", line 51, in create
    pdf_string = print_danfe(account_invoice)
  File "/opt/openerp-8.0/odoo-brazil-eletronic-documents/nfe/sped/nfe/processing/xml.py", line 145, in print_danfe
    danfe.gerar_danfe()
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/nfe/danfe/danfe.py", line 243, in gerar_danfe
    self.danfe.generate_by(PDFGenerator, filename=danfe_pdf)
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/base.py", line 435, in generate_by
    return generator.execute()
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/generators/pdf.py", line 100, in execute
    self.render_bands()
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/generators/base.py", line 548, in render_bands
    self.start_new_page()
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/generators/base.py", line 436, in start_new_page
    self.render_page_header()
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/generators/pdf.py", line 234, in render_page_header
    update_top=False,
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/generators/base.py", line 373, in render_band
    top_position)
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/generators/base.py", line 222, in render_element
    para = self.make_paragraph(widget.text, self.make_paragraph_style(band, widget.style))
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/widgets.py", line 253, in <lambda>
    text = property(lambda self: self._text(), _set_text)
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/widgets.py", line 238, in _text
    value = getattr(self, 'action_'+self.action)()
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/widgets.py", line 191, in action_value
    return self.get_object_value(attribute_name=attribute_name)
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/widgets.py", line 160, in get_object_value
    value = get_attr_value(instance, attribute_name)
  File "/usr/local/lib/python2.7/dist-packages/Geraldo-0.4.17-py2.7.egg/geraldo/utils.py", line 98, in get_attr_value
    raise AttributeNotFound('There is no attribute nor key "%s" in the object "%s"'%(parts[0], repr(obj)))
AttributeNotFound: There is no attribute nor key "NFe" in the object "None"
2015-08-14 21:11:00,481 9995 ERROR impala openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/openerp-8.0/odoo/openerp/addons/web/controllers/main.py", line 69, in wrap
    return f(_args, *_kwargs)
  File "/opt/openerp-8.0/odoo/openerp/addons/web/controllers/main.py", line 1563, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/http.py", line 872, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/service/report.py", line 141, in exp_report_get
    return _check_report(report_id)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/service/report.py", line 119, in _check_report
    raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: (u'There is no attribute nor key "NFe" in the object "None"', (<class 'geraldo.exceptions.AttributeNotFound'>, AttributeNotFound(u'There is no attribute nor key "NFe" in the object "None"',), <traceback object at 0x7f4646389e18>))

**Comment by danimaribeiro** [comment]
Em qual etapa está tentando gerar o Danfe, e quais versões do pysped e do geraldo está utilizando?

**Comment by yk2kus** [comment]
@danimaribeiro : Sorry for writing in english, I do not understand Portuguese well, I am on step of 
"Transmitir" ,  "Pré-Visualizar" . Version of geraldo is '0.4.17' and pysped is '0.1.2' .

**Comment by danimaribeiro** [comment]
Did you install from odoo-brazil branch pysped and geraldo?

**Comment by yk2kus** [comment]
No, I think I installed from https://github.com/aricaldeira

**Comment by danimaribeiro** [comment]
At least PySped should be installed from here:
https://github.com/odoo-brazil/PySPED

Geraldo don't have any change.

**Comment by yk2kus** [comment]
so I installed PySped from odoo-brazil, it gets installed but terminates while installing PySMLSec with logs below 

pysped.exemplos.008_versao_2.00_inutilizar_notas: module references **file**
creating dist
creating 'dist/PySPED-0.1.2-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing PySPED-0.1.2-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg
Extracting PySPED-0.1.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
PySPED 0.1.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg
Processing dependencies for PySPED==0.1.2
Searching for PyXMLSec>=0.3.0
Reading https://pypi.python.org/simple/PyXMLSec/
Best match: pyxmlsec 0.3.1
Downloading http://labs.libre-entreprise.org/frs/download.php/897/pyxmlsec-0.3.1.tar.gz
Processing pyxmlsec-0.3.1.tar.gz
Writing /tmp/easy_install-v6hR_M/pyxmlsec-0.3.1/setup.cfg
Running pyxmlsec-0.3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-v6hR_M/pyxmlsec-0.3.1/egg-dist-tmp-PVdGVr
Error : cannot get XMLSec1 pre-processor and compiler flags
Error : cannot get XMLSec1 linker flags
Warning : cflag sh: skipped
Warning : cflag 1: skipped
Warning : cflag xmlsec1-config: skipped
Warning : cflag not skipped
Warning : cflag found skipped
Warning : linker flag sh: skipped
Warning : linker flag 1: skipped
Warning : linker flag xmlsec1-config: skipped
Warning : linker flag not skipped
Warning : linker flag found skipped
warning: no previously-included files found matching 'examples/vrac_'
warning: no previously-included files found matching 'examples/_~'
warning: no previously-included files found matching 'docs/cours/*'
In file included from wrap_objs.c:14:0:
wrap_objs.h:10:27: fatal error: xmlsec/xmlsec.h: No such file or directory
 #include <xmlsec/xmlsec.h>
                           ^
compilation terminated.

**Comment by yk2kus** [comment]
updated PySped from odoo-brasil  still getting same error 

There is no attribute nor key "NFe" in the object "None"

<class 'geraldo.exceptions.AttributeNotFound'>,There is no attribute nor key "NFe" in the object "None",<traceback object at 0x7fb368cac2d8>

**Comment by yk2kus** [comment]
the error is raised from https://github.com/gltn/stdm/blob/master/third_party/geraldo/utils.py#L98 line
it might be some configuration issue?

**Comment by yk2kus** [comment]
the error is raised from https://github.com/odoo-brazil/geraldo/blob/master/geraldo/utils.py#L104 line
it might be some configuration issue?

**Comment by yk2kus** [comment]
So I cleaned old installation did new installation from odoo-brazil, now I am getting error in confirmation of invoices from https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/blob/8.0/nfe/account_invoice.py#L76

logs:

  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/openerp-8.0/odoo-brazil-eletronic-documents/nfe/account_invoice.py", line 81, in nfe_export
    _(u'Erro na validação da NFe!'), erro)
except_orm: <unprintable except_orm object>
2015-08-17 16:26:32,599 681 ERROR impala openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp-8.0/odoo/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch
    result = request.dispatch()
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/http.py", line 583, in dispatch
    return self._handle_exception(e)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/http.py", line 537, in _handle_exception
    'data': serialize_exception(exception)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/http.py", line 589, in serialize_exception
    "message": ustr(e),
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/loglevels.py", line 77, in ustr
    return exception_to_unicode(value)
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/loglevels.py", line 100, in exception_to_unicode
    return "\n".join((ustr(a) for a in e.args))
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/loglevels.py", line 100, in <genexpr>
    return "\n".join((ustr(a) for a in e.args))
  File "/home/ubuntu/Dropbox/openerp-8.0/odoo-8.0-20150322/openerp/loglevels.py", line 86, in ustr
    raise UnicodeError('unable to convert %r' % (value,))
  File "xmlerror.pxi", line 286, in lxml.etree._ListErrorLog.__repr__ (src/lxml/lxml.etree.c:33201)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xff' in position 173: ordinal not in range(128)
127.0.0.1 - - [2015-08-17 16:26:32] "POST /web/dataset/exec_workflow HTTP/1.0" 200 2664 9.062442
2015-08-17 16:26:35,256 681 INFO tracelayout openerp.modules.loading: loading 1 modules...
2015-08-17 16:26:35,269 681 INFO tracelayout openerp.modules.loading: 1 modules loaded in 0.01s

**Comment by yk2kus** [comment]
last error is fixed with https://github.com/chicocvenancio/odoo-brazil-eletronic-documents/commit/df34dcd73e33783aecd3c27b0b50691bf04ee935 , thanks @chicocvenancio !

now pre visualizar DANFE is working for me but "Transmitir" button sends me to statge "Erro de autorização da Receita" without any error log.

**Comment by danimaribeiro** [comment]
What exactly chicocvenancio fixed?
Check the eletronic events and look at the generated xmls.

**Comment by yk2kus** [comment]
@danimaribeiro  where can I look for electronic events and xmls?

**Comment by chicocvenancio** [comment]
And that revision was made in error...

**Comment by yk2kus** [comment]
well, found events, they are created with message "Rejeição: Cabeçalho - Versão do arquivo XML não suportada".

**Comment by yk2kus** [comment]
So what I understood so far is .xml is generated with versao="2.00" but only "3.10" is supported so what do I need to update to generate xml with 3.10? 
Versão NFe in odoo is already selected 3.10.

**Comment by chicocvenancio** [comment]
Check the company fiscal settings.

Chico Venancio
CEO e Diretor de Criação
VM TECH - (98)8800-2743
Em 17/08/2015 14:43, "Yogesh Kushwaha" notifications@github.com escreveu:

**Comment by yk2kus** [comment]
It seems it is bug, I have already set '3.10' for field Versão NFe, in Settings -> Companies -> Fiscal(Tab) -> Product(Tab) ->NFe (Tab)
