### ISSUE TITLE
Erro ao Baixar o arquivo 

### ISSUE THREAD

**Issue by pauloneda** [Trust-Code/odoo-brazil-eletronic-documents#8]
openerp.addons.nfe_mde.nfe_schedule: 'ascii' codec can't decode byte 0xc3 in position 400: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/odoo/nfe/nfe_mde/nfe_schedule.py", line 40, in schedule_download
    nfe_result = distribuicao_nfe(company, company.last_nsu_nfe)
  File "/opt/odoo/nfe/nfe_mde/service/mde.py", line 77, in distribuicao_nfe
    orig_file_desc = gzip.GzipFile(
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 400: ordinal not in range(128)

**Comment by danimaribeiro** [comment]
Infelizmente não consigo reproduzir o problema.
